Allow to specify clientProperties
hufsm/rabbot pull request #17
Opened 2018-11-23 07:30 UTC by ptusch

clientProperties will give us hints about whatever we want. We could specify it in the amqpProtocolAdapter or as client option.

2018-11-26 13:39 UTC, stheuer requested changes
Please Fix two intendations and merge

2018-11-26 13:39 UTC, stheuer commented on src/amqp/connection.js
> +  var clientProperties = getOption( parameters, "clientProperties");
intendation

2018-11-26 13:39 UTC, stheuer commented on src/amqp/connection.js
> +  this.options.clientProperties = Object.assign(CLIENT_PROPERTIES, clientProperties);
intendation

2018-12-03 12:02 UTC, ptusch commented on src/amqp/connection.js
> +  var clientProperties = getOption( parameters, "clientProperties");
Done: 1eca555

2018-12-03 12:02 UTC, ptusch commented on src/amqp/connection.js
> +  this.options.clientProperties = Object.assign(CLIENT_PROPERTIES, clientProperties);
Done: 1eca555

2018-12-03 12:04 UTC, stheuer approved these changes

2018-12-03 12:04 UTC, merged